# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_addmainurls'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
                ('rank', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='addmainurls',
            options={'verbose_name': 'ссылка', 'verbose_name_plural': 'ссылки'},
        ),
        migrations.AlterModelOptions(
            name='addurlsintable',
            options={'verbose_name': 'Таблица ', 'verbose_name_plural': 'Таблица для расчет'},
        ),
    ]
